services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:17-alpine
    container_name: voz-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
volumes:
  postgres_data: